using System;
using System.Xml.Serialization;

namespace EbixExchange.LifeSpeed.ConsumeClientServices
{
    /// <summary>
    /// This class is used to provide information of the transaction that is being used in the web request.
    /// </summary>
    [Serializable]
    public class BaseTXLife
    {
        /// <summary>
        /// Identifier of the primary object for the request
        /// </summary>
        [XmlAttribute("PrimaryObjectID")]
        public string PrimaryObjectID
        {
            get;
            set;
        }

        /// <summary>
        /// Unique GUID generated by ebixexchange system that is associated with this request
        /// </summary>
        [XmlElement("TransRefGuid")]
        public Guid TransactionGuid
        {
            get;
            set;
        }

        /// <summary>
        /// Type of the ACORD transaction request 
        /// </summary>
        [XmlElement("TransType")]
        public TypeCodeContainer TransType
        {
            get;
            set;
        }

        /// <summary>
        /// Subtype of the ACORD transaction request 
        /// </summary>
        [XmlElement("TransSubType")]
        public TypeCodeContainer TransSubType
        {
            get;
            set;
        }

        /// <summary>
        /// Date that this request was made in YYYY-MM-DD format
        /// </summary>
        [XmlElement("TransExeDate")]
        public string TransactionExeDate
        {
            get;
            set;
        }

        /// <summary>
        /// Time that this request was made in
        /// </summary>
        [XmlElement("TransExeTime")]
        public string TransactionExeTime
        {
            get;
            set;
        }
    }
}